import type { DashboardData } from "@/lib/types";

export function createDemoData(): DashboardData {
  return {
    properties: [
      {
        id: "property-1",
        name: "Marin Mid-Century Estate",
        city: "San Rafael",
        state: "CA",
        saleDeadline: "2026-04-28",
        notes: "Prioritize audio, teak furniture, and art lots.",
      },
    ],
    reviewQueue: [
      {
        id: "item-1",
        propertyId: "property-1",
        title: "Pioneer PL-518 turntable",
        category: "audio",
        confidence: 0.91,
        state: "needs_review",
        needsPhoto: false,
        riskFlags: ["untested"],
        fulfillmentMode: "shipping",
        priceLowCents: 18000,
        priceHighCents: 26000,
        conditionSummary: "Used with light dust cover wear.",
        evidence: { labelVisible: true, powerObserved: false },
      },
      {
        id: "item-2",
        propertyId: "property-1",
        title: "Teak nesting tables",
        category: "furniture",
        confidence: 0.42,
        state: "needs_photo",
        needsPhoto: true,
        riskFlags: ["needs_photo"],
        fulfillmentMode: "pickup",
        priceLowCents: 22000,
        priceHighCents: 34000,
        conditionSummary: "Transcript matched item mention but hero frame is weak.",
        evidence: { transcriptMatched: true, heroFrameQuality: 0.31 },
      },
      {
        id: "item-3",
        propertyId: "property-1",
        title: "Two teak dining chairs",
        category: "furniture",
        confidence: 0.84,
        state: "approved",
        needsPhoto: false,
        riskFlags: [],
        fulfillmentMode: "local_delivery",
        priceLowCents: 14000,
        priceHighCents: 22000,
        conditionSummary: "Solid frames, fabric needs cleaning.",
        evidence: { quantity: 2, duplicateKey: "teak-chair" },
        groupId: "group-1",
      },
    ],
    listingDrafts: [
      {
        id: "draft-1",
        candidateItemId: "item-1",
        title: "Pioneer PL-518 Direct Drive Turntable",
        description: "Vintage Pioneer turntable from a Marin estate. Sold as untested.",
        listingState: "ready_to_publish",
        shippingProfile: { packagePreset: "medium_turntable", mode: "shipping" },
      },
      {
        id: "draft-2",
        candidateItemId: "item-3",
        title: "Set of Two Teak Dining Chairs",
        description: "Mid-century teak dining chairs sold as a pair.",
        listingState: "published",
        shippingProfile: { packagePreset: "local_pair", mode: "local_delivery" },
        externalListingId: "EBY-draft-2",
        externalUrl: "https://www.ebay.com/itm/EBY-draft-2",
      },
      {
        id: "draft-3",
        candidateItemId: "item-3",
        title: "Set of Two Teak Dining Chairs - Duplicate Channel Copy",
        description: "Stale sibling listing used to prove duplicate-sale shutdown.",
        listingState: "published",
        shippingProfile: { packagePreset: "local_pair", mode: "local_delivery" },
        externalListingId: "EBY-draft-3",
        externalUrl: "https://www.ebay.com/itm/EBY-draft-3",
      },
    ],
    orders: [
      {
        id: "order-1",
        listingDraftId: "draft-1",
        buyerName: "Sam Collector",
        state: "paid",
        fulfillmentMode: "shipping",
        salePriceCents: 23900,
        highValue: false,
      },
      {
        id: "order-2",
        listingDraftId: "draft-2",
        buyerName: "Mina Local",
        state: "paid",
        fulfillmentMode: "local_delivery",
        salePriceCents: 18900,
        highValue: true,
      },
      {
        id: "order-3",
        listingDraftId: "draft-2",
        buyerName: "Jon Pickup",
        state: "paid",
        fulfillmentMode: "pickup",
        salePriceCents: 12000,
        highValue: false,
      },
    ],
  };
}
